<h2>ILLSLNPKoha - Fernleihebestellungen werden ausschließlich über ein externes Portal angelegt.<br>
Das manuelle Erfassen einer ILLSLNPKoha - Fernleihebestellung ist nicht vorgesehen.</h2>


<a class="cancel" id="cancelbutton" name="cancelbutton" href="/cgi-bin/koha/ill/ill-requests.pl">Abbrechen</a>

[% BLOCK backend_jsinclude %]
    <style id="antiClickjack">body{display:none !important;}</style>
    [% INCLUDE 'js_includes.inc' %]

    <script type= "text/javascript">
    </script>
[% END %]

