<h2>ILLSLNPKoha - Fernleihebestellungen werden ausschließlich über ein externes Portal angelegt.<br>
Das manuelle Erfassen einer ILLSLNPKoha - Fernleihebestellung ist nicht vorgesehen.</h2>


<a class="cancel" id="cancelbutton" name="cancelbutton" href="/cgi-bin/koha/ill/ill-requests.pl">Abbrechen</a>

[% BLOCK backend_jsinclude %]
    [% Asset.js("lib/jquery/jquery.js") | $raw %]
    <script type= "text/javascript">

    </script>
[% END %]

